### PR TITLE
Fix 10 sec delay when switching modes

### PR DESCRIPTION
**Pull request by vkhromov**
Issue #7 

For some reason, setting the origin to the same position causes delay up
to 10 seconds in the `CGCompleteDisplayConfiguration()` function.

Fix that by not updating the origin when it hasn't changed.

Before:
```bash
$ time displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(2560,-480) degree:0"
displayplacer      0.05s user 0.10s system 31% cpu 0.499 total
$ time displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(2560,-480) degree:0"
displayplacer      2.08s user 2.20s system 42% cpu 10.091 total
$ time displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(1600,-480) degree:0"
displayplacer      0.05s user 0.09s system 24% cpu 0.558 total
$ time displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(1600,-480) degree:0"
displayplacer      1.99s user 2.13s system 40% cpu 10.147 total
```

After:
```bash
$ time ./displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(2560,-480) degree:0"
./displayplacer      0.04s user 0.08s system 23% cpu 0.539 total
$ time ./displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(2560,-480) degree:0"
./displayplacer      0.01s user 0.01s system 20% cpu 0.124 total
$ time ./displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(1600,-480) degree:0"
./displayplacer      0.05s user 0.10s system 30% cpu 0.495 total
$ time ./displayplacer "id:9754CAAE-824F-65E6-2D1A-278874E2059E res:1600x900 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:175CFE0E-D1A0-10DC-4168-EAB9721CAF2A res:1024x640 color_depth:4 scaling:on origin:(-1024,113) degree:0" "id:4991ECC3-A7F9-DCD7-572C-C40162BF8A3D res:1600x900 hz:60 color_depth:8 scaling:off origin:(1600,0) degree:0" "id:CB145C55-1943-861B-5530-1F98574A9FF1 res:640x480 hz:60 color_depth:8 scaling:off origin:(1600,-480) degree:0"
./displayplacer      0.02s user 0.02s system 18% cpu 0.186 total
```

### CODE REVIEW

**Comment by jakehilborn** [comment]
Great find! I'll test this out on my machine and see if I get similar results. I'll try to get this merged by the end of the weekend.

**Comment by alex-the-man** [comment]
I tested this change on my MBP 16" on 10.15 and it's working.

**Comment by thesofakillers** [comment]
anything blocking a merge here?

**Comment by jakehilborn** [comment]
Thank you for looking into this and submitting a patch!

**Comment by jakehilborn** [comment]
@vkhromov @alex-the-man @thesofakillers This is included in [release v1.3.0](https://github.com/jakehilborn/displayplacer/releases)

**Pull request merged**
